/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author matheusferreira
 */
public class cadastrarJob extends javax.swing.JFrame {
    /**
     * Creates new form cadastrarJob
     */
    public cadastrarJob() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        nomeDoProjetoTitle = new javax.swing.JLabel();
        nomeDoProjetoTextField = new javax.swing.JTextField();
        nomeDoFotografoTitle = new javax.swing.JLabel();
        nomeDoFotografoTextField = new javax.swing.JTextField();
        nomeDoClienteTitle = new javax.swing.JLabel();
        nomeDoClienteTextField = new javax.swing.JTextField();
        nomeDoModeloTitle = new javax.swing.JLabel();
        nomeDoModeloTextField = new javax.swing.JTextField();
        dataDeInicioTitle = new javax.swing.JLabel();
        dataDeInicioTextField = new javax.swing.JTextField();
        dataDeFinalizacaoTitle = new javax.swing.JLabel();
        dataDeFinalizacaoTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacoesTextArea = new javax.swing.JTextArea();
        cadastrarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        observacoesTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("Insira as informações do projeto que deseja cadastrar:");

        nomeDoProjetoTitle.setText("Nome do Projeto:");

        nomeDoProjetoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDoProjetoTextFieldActionPerformed(evt);
            }
        });

        nomeDoFotografoTitle.setText("Nome do(a) Fotógrafo:");

        nomeDoFotografoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDoFotografoTextFieldActionPerformed(evt);
            }
        });

        nomeDoClienteTitle.setText("Nome do(a) Cliente:");

        nomeDoClienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDoClienteTextFieldActionPerformed(evt);
            }
        });

        nomeDoModeloTitle.setText("Nome do(a) Modelo:");

        nomeDoModeloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDoModeloTextFieldActionPerformed(evt);
            }
        });

        dataDeInicioTitle.setText("Data de Início:");

        dataDeInicioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDeInicioTextFieldActionPerformed(evt);
            }
        });

        dataDeFinalizacaoTitle.setText("Data de Finalização:");

        dataDeFinalizacaoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDeFinalizacaoTextFieldActionPerformed(evt);
            }
        });

        observacoesTextArea.setColumns(20);
        observacoesTextArea.setRows(5);
        jScrollPane1.setViewportView(observacoesTextArea);

        cadastrarButton.setText("CADASTRAR NOVO PROJETO");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        voltarButton.setText("< Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        observacoesTitle.setText("Observações:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomeDoClienteTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nomeDoClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomeDoFotografoTitle)
                                .addGap(18, 18, 18)
                                .addComponent(nomeDoFotografoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomeDoProjetoTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nomeDoProjetoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeDoModeloTitle)
                                    .addComponent(dataDeInicioTitle)
                                    .addComponent(dataDeFinalizacaoTitle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeDoModeloTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(dataDeInicioTextField)
                                    .addComponent(dataDeFinalizacaoTextField)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(observacoesTitle, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(voltarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sairButton)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(title)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDoProjetoTitle)
                    .addComponent(nomeDoProjetoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDoFotografoTitle)
                    .addComponent(nomeDoFotografoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDoClienteTitle)
                    .addComponent(nomeDoClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDoModeloTitle)
                    .addComponent(nomeDoModeloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataDeInicioTitle)
                    .addComponent(dataDeInicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataDeFinalizacaoTitle)
                    .addComponent(dataDeFinalizacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(observacoesTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sairButton)
                    .addComponent(voltarButton))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeDoProjetoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDoProjetoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDoProjetoTextFieldActionPerformed

    private void nomeDoFotografoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDoFotografoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDoFotografoTextFieldActionPerformed

    private void nomeDoClienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDoClienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDoClienteTextFieldActionPerformed

    private void nomeDoModeloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDoModeloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDoModeloTextFieldActionPerformed

    private void dataDeInicioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDeInicioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDeInicioTextFieldActionPerformed

    private void dataDeFinalizacaoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDeFinalizacaoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDeFinalizacaoTextFieldActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
    String url = "jdbc:mysql://localhost:3306/agendaFotografo";
    String username = "root";
    String password = "admin123";

    try {
        // Estabelecer a conexão com o banco de dados
        Connection connection = DriverManager.getConnection(url, username, password);

        // Preparar a consulta SQL para inserir os dados
        String sql = "INSERT INTO Jobs (nomeDoProjeto, nomeDoFotografo, nomeDoCliente, nomeDoModelo, dataDeInicio, dataDeFinalizacao, observacoes) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement statement = connection.prepareStatement(sql);

        // Preencher os parâmetros da consulta com os valores dos campos de texto
        statement.setString(1, nomeDoProjetoTextField.getText());
        statement.setString(2, nomeDoFotografoTextField.getText());
        statement.setString(3, nomeDoClienteTextField.getText());
        statement.setString(4, nomeDoModeloTextField.getText());
        statement.setString(5, dataDeInicioTextField.getText());
        statement.setString(6, dataDeFinalizacaoTextField.getText());
        statement.setString(7, observacoesTextArea.getText());

        // Executar a consulta SQL para inserir os dados
        int rowsInserted = statement.executeUpdate();

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(null, "Job Cadastrado com sucesso!");
        }

        // Fechar a conexão com o banco de dados
        connection.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Ocorreu um erro ao cadastrar o Job.");
    }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
    telaInicial telaInicial = new telaInicial();
    telaInicial.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
    System.exit(0);
    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrarJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrarJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrarJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrarJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrarJob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField dataDeFinalizacaoTextField;
    private javax.swing.JLabel dataDeFinalizacaoTitle;
    private javax.swing.JTextField dataDeInicioTextField;
    private javax.swing.JLabel dataDeInicioTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeDoClienteTextField;
    private javax.swing.JLabel nomeDoClienteTitle;
    private javax.swing.JTextField nomeDoFotografoTextField;
    private javax.swing.JLabel nomeDoFotografoTitle;
    private javax.swing.JTextField nomeDoModeloTextField;
    private javax.swing.JLabel nomeDoModeloTitle;
    private javax.swing.JTextField nomeDoProjetoTextField;
    private javax.swing.JLabel nomeDoProjetoTitle;
    private javax.swing.JTextArea observacoesTextArea;
    private javax.swing.JLabel observacoesTitle;
    private javax.swing.JButton sairButton;
    private javax.swing.JLabel title;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
